# Generated by Django 3.1.2 on 2022-08-24 05:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=127)),
                ('companyId', models.IntegerField(default=-1)),
                ('countryId', models.IntegerField(default=-1)),
                ('marketId', models.IntegerField(default=-1)),
                ('sectorId', models.IntegerField(default=-1)),
                ('branchId', models.IntegerField(default=-1)),
                ('countryUrlName', models.CharField(default='NOURL', max_length=127)),
                ('shortName', models.CharField(default='NOSHORTNAME', max_length=127)),
                ('corruptData', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorldKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='NONAME', max_length=127)),
                ('name', models.CharField(default='NONAME', max_length=127)),
                ('timestamp', models.DateTimeField(blank=True, default=None)),
                ('value', models.FloatField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStockDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, default=None)),
                ('close', models.FloatField(default=-1)),
                ('open', models.FloatField(default=-1)),
                ('high', models.FloatField(default=-1)),
                ('low', models.FloatField(default=-1)),
                ('volume', models.FloatField(default=-1)),
                ('daydiff_volume', models.FloatField(default=-1)),
                ('comapny', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crawler.companies')),
            ],
        ),
        migrations.CreateModel(
            name='CollectorSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerName', models.CharField(default='Unnamed', max_length=127)),
                ('daysToCollect', models.IntegerField(default=7)),
                ('RSIintervall', models.IntegerField(default=-1)),
                ('ValidStockdataLimit', models.IntegerField(default=-1)),
                ('avrageWindow', models.IntegerField(default=-1)),
                ('firstInculdedDate', models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 24, 7, 6, 25, 60095))),
                ('lastIncudedDate', models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 24, 7, 6, 25, 60095))),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('fileName', models.CharField(default='NONAME', max_length=127)),
                ('comapnys', models.ManyToManyField(blank=True, related_name='CollectedCompanies', to='crawler.Companies')),
                ('worldKPIs', models.ManyToManyField(blank=True, related_name='CollectedCKPI', to='crawler.WorldKPI')),
            ],
        ),
    ]
