# Generated by Django 3.1.2 on 2022-08-28 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorsettings',
            name='firstInculdedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 28, 18, 15, 46, 679196)),
        ),
        migrations.AlterField(
            model_name='collectorsettings',
            name='lastIncudedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 28, 18, 15, 46, 679196)),
        ),
    ]
