# Generated by Django 3.1.2 on 2022-08-24 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorsettings',
            name='firstInculdedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 24, 7, 11, 5, 820255)),
        ),
        migrations.AlterField(
            model_name='collectorsettings',
            name='lastIncudedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 24, 7, 11, 5, 820255)),
        ),
    ]
