# Generated by Django 3.1.2 on 2022-08-28 16:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0002_auto_20220828_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networkName', models.CharField(default='NONAME', max_length=127)),
                ('trainingDataWindow', models.IntegerField(default=5)),
                ('reSeed', models.BooleanField(default=False)),
                ('weightLimitLow', models.FloatField(default=-0.1)),
                ('weightLimitHigh', models.FloatField(default=0.1)),
                ('biasLow', models.FloatField(default=0.1)),
                ('biasHigh', models.FloatField(default=-1)),
                ('predictionPart', models.FloatField(default=0.2)),
                ('stockTrainingTime', models.IntegerField(default=60)),
                ('modelPath', models.CharField(blank=True, default='', max_length=127)),
                ('lR', models.FloatField(default=0.01)),
                ('mockData', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('lastrun', models.DateTimeField(auto_now=True)),
                ('predictingDays', models.IntegerField(default=7)),
                ('inputDim', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), size=None)),
                ('hidden_dim', models.IntegerField(default=-1)),
                ('output_dim', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), size=None)),
                ('n_layers', models.IntegerField(default=-1)),
                ('batchsize', models.IntegerField(default=-1)),
                ('xdrop_prob', models.FloatField(default=0.01)),
                ('collectorSetting', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='crawler.collectorsettings')),
                ('targets', models.ManyToManyField(blank=True, related_name='MyTargets', to='crawler.Companies')),
            ],
        ),
    ]
