# Generated by Django 4.0.6 on 2022-08-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daysToInclude', models.IntegerField(default=365)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.IntegerField(default=-1)),
                ('countryId', models.IntegerField(default=-1)),
                ('marketId', models.IntegerField(default=-1)),
                ('sectorId', models.IntegerField(default=-1)),
                ('branchId', models.IntegerField(default=-1)),
                ('countryUrlName', models.CharField(default='NOURL', max_length=127)),
                ('shortName', models.CharField(default='NOSHORTNAME', max_length=127)),
            ],
        ),
    ]
