# Generated by Django 4.0.6 on 2022-08-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='name',
            field=models.CharField(default='NONAME', max_length=127),
        ),
    ]
