# Generated by Django 4.0.6 on 2022-08-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0002_companies_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='NOTYPE', max_length=127)),
                ('refId', models.IntegerField(default=-1)),
                ('refName', models.CharField(default='NOREF', max_length=127)),
                ('countryId', models.IntegerField(blank=True, default=None)),
                ('marketId', models.IntegerField(blank=True, default=None)),
                ('sectorId', models.IntegerField(blank=True, default=None)),
                ('branchId', models.IntegerField(blank=True, default=None)),
                ('timestamp', models.DateTimeField(blank=True, default=None)),
            ],
        ),
    ]
