# Generated by Django 4.0.6 on 2022-08-14 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0003_datapoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStockDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, default=None)),
                ('close', models.FloatField(default=-1)),
                ('open', models.FloatField(default=-1)),
                ('high', models.FloatField(default=-1)),
                ('low', models.FloatField(default=-1)),
                ('volume', models.FloatField(default=-1)),
                ('daydiff_volume', models.FloatField(default=-1)),
                ('comapny', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='datacollector.companies')),
            ],
        ),
        migrations.DeleteModel(
            name='DataPoint',
        ),
    ]
