# Generated by Django 3.1.2 on 2022-08-16 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0004_companystockday_delete_datapoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorsettings',
            name='RSIintervall',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='collectorsettings',
            name='ValidStockdataLimit',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='collectorsettings',
            name='avrageWindow',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='collectorsettings',
            name='firstInculdedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='collectorsettings',
            name='lastIncudedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='collectorsettings',
            name='daysToInclude',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='collectorsettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companystockday',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
