# Generated by Django 3.1.2 on 2022-08-17 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0006_auto_20220816_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='NONAME', max_length=127)),
                ('name', models.CharField(default='NONAME', max_length=127)),
                ('timestamp', models.DateTimeField(blank=True, default=None)),
                ('value', models.FloatField(default=-1)),
            ],
        ),
        migrations.AlterField(
            model_name='collectorsettings',
            name='firstInculdedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 17, 20, 25, 42, 478855)),
        ),
        migrations.AlterField(
            model_name='collectorsettings',
            name='lastIncudedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 17, 20, 25, 42, 478855)),
        ),
    ]
