# Generated by Django 3.1.2 on 2022-08-18 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0007_auto_20220817_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='corruptData',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collectorsettings',
            name='firstInculdedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 18, 5, 26, 19, 415618)),
        ),
        migrations.AlterField(
            model_name='collectorsettings',
            name='lastIncudedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 18, 5, 26, 19, 415618)),
        ),
        migrations.AlterField(
            model_name='companystockday',
            name='timestamp',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.CreateModel(
            name='TrainingDataRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('networkName', models.CharField(default='NONAME', max_length=127)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('fileName', models.CharField(default='NONAME', max_length=127)),
                ('comapnys', models.ManyToManyField(blank=True, to='datacollector.Companies')),
                ('worldKPIs', models.ManyToManyField(blank=True, to='datacollector.WorldKPI')),
            ],
        ),
    ]
