# Generated by Django 3.1.2 on 2022-08-18 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0008_auto_20220818_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorsettings',
            name='firstInculdedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 18, 5, 50, 38, 241386)),
        ),
        migrations.AlterField(
            model_name='collectorsettings',
            name='lastIncudedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 18, 5, 50, 38, 241386)),
        ),
        migrations.AlterField(
            model_name='companystockday',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
