# Generated by Django 3.1.2 on 2022-08-18 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollector', '0009_auto_20220818_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdataregister',
            name='predictingDays',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='trainingdataregister',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='MyTargets', to='datacollector.Companies'),
        ),
        migrations.AlterField(
            model_name='collectorsettings',
            name='firstInculdedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 18, 6, 39, 13, 62157)),
        ),
        migrations.AlterField(
            model_name='collectorsettings',
            name='lastIncudedDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 18, 6, 39, 13, 62157)),
        ),
    ]
